### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by moonwalker-ljh** [jedyang97/MTAG#4]
杨同学你好，我对你的研究比较感兴趣，准备复现你的实验，但是你所提到的实验数据集已经无法在你提供的网址下载了。
请问能否给我提供一下你已经下载的数据集呢？

**Comment by jedyang97** [comment]
Hi @moonwalker-ljh ,

Thanks for bringing this to my attention! I am contacting the owner of these data - apparently, there were some concerns about sharing these data, which was why the link was taken down. I will share with you the latest update as soon as I hear back. Thanks for your patience!

**Comment by jedyang97** [comment]
@moonwalker-ljh Thanks for your patience. I have updated the README to include new links for downloading the data.

**Comment by moonwalker-ljh** [comment]
@jedyang97 I downloaded the new dataset you provided, but got the error 'pickle data was truncated' when loading the pkl file. I also found that the size of all pkl files is not normal, only 8.5MB. could you please tell me if there is an error when uploading the dataset?

**Comment by jedyang97** [comment]
Oh you are right, let me re-upload. Sorry about the confusion!

**Comment by jedyang97** [comment]
@moonwalker-ljh I have updated the links. Try again and let me know if it still doesn't work!

**Comment by moonwalker-ljh** [comment]
OK，i'll try again.

**Comment by moonwalker-ljh** [comment]
@jedyang97 Also, do you have a dataset for MOSEI? And if i want to use MOSEI, do i need to use the same dataset structure as MOSI? Because I saw that there is code about MOSEI.

**Comment by jedyang97** [comment]
@moonwalker-ljh I have included it in the "Other datasets" link in the README page - try refresh that link and you should find MOSEI. It should be the same format at MOSI.
