### ISSUE TITLE
Question about mosi datasets' preprocessing

### ISSUE THREAD

**Issue by sunjieemm** [jedyang97/MTAG#5]
Hi, I have a confusion about the mosi datasets' preprocessing. 
I found two versions of the mosi dataset. For t, a, v, one has dimension with [300,5,20] respectively, rather than another one has dimension with [300,74,47], whatever aligned or unaligned.  ​As far as I know, MOSI audio and vision modality features extracted by COVAREP and Facet have 74 and 47 feature dimensions. So is there a different preprocessing?
Looking forward to hearing from you!

**Comment by jedyang97** [comment]
Hi @sunjieemm, thanks for your interest in MTAG!

We were using data pre-processed by the [Tensor Fusion](https://arxiv.org/abs/1707.07250) paper. I took a quick look and in page 4 of the paper, the authors described briefly about pre-processing:

> A set of 20 Facial Action Units (Ekman et al., 1980), indicating detailed muscle movements on the face, are also extracted using FACET

This is likely what the 20 in the visual modality means.

As for the acoustic modality, the authors also have a detailed paragraph explaining how it is extracted with COVAREP. That paragraph is a bit long so I will point to the original paper for more detailed information.

Hope this helps!
